### PR TITLE
added templates and arguments  to solve issue 11,12 and 13

### PR DESCRIPTION
**Pull request by Ihure**
added templates and arguments  to solve issue 11,12 and 13

### CODE REVIEW

**Comment by davidsemakula** [comment]
@Ihure looking good, will review and test more thoroughly and send you some feedback

I don't see the functions being used yet however

**Comment by Ihure** [comment]
in notifications,py from line 927 to 1022

**Comment by davidsemakula** [comment]
@Ihure I can see the functions are defined here https://github.com/Ihure/tunga-api/blob/develop/tunga_tasks/notifications.py#L927-L1022 but they aren't being called anywhere

**Comment by Ihure** [comment]
@davidsemakula i call them at https://github.com/Ihure/tunga-api/blob/develop/tunga_tasks/signals.py#L198-L207 but come to think of it I could just add those arguments at https://github.com/Ihure/tunga-api/blob/develop/tunga_tasks/notifications.py#L894-L897

**Comment by davidsemakula** [comment]
@Ihure nice I missed that, looks good ... reviewing

**Pull request merged**
